config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'bases/new'

  get 'attendances/update'

  get 'users/new'

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  get     '/login', to: 'sessions#new'
  post    '/login', to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'
  
  #勤怠修正ログ
  resources :attendance_logs
  
  
  resources :users do
    collection {post :import}
    member do
      get   'edit_basic_info'
      patch 'update_basic_info'
      get   'working_employee'
      get   'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get   'search'
      
      get   'attendances/change_confirmation'
      post  'attendances/change_confirmation'
      patch 'attendances/change_confirmation'
      
      get   'attendances/change_confirmation_form'
      post  'attendances/change_confirmation_form'
      
      get   'attendances/index'
      post  'attendances/index'
      patch 'attendances/index'
      
    end
    resources :attendances, only: :update do
      member do
        #残業申請送信フォーム
        get   'apply_overtime_form'
  
        #残業申請
        patch 'apply_overtime'
        
        #残業申請のお知らせフォーム
        get   'update_overtime_form'
        
        #残業承認
        patch 'update_overtime'
        
      end
      collection do
        #一ヶ月分の申請
        patch 'monthly_confirmation'

        #上長画面一ヶ月分勤怠申請のお知らせフォーム
        get   'monthly_confirmation_form'
        patch 'monthly_update'
        
        get   'csv_output'
      end
    end
  end
  
  resources :bases
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  
  validates :name, presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :affiliation, length: { in: 2..50 }, allow_blank: true
  validates :basic_time, presence: true
  validates :designated_work_start_time, presence: true
  validates :designated_work_end_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # 追加　どこからでもUser.sperior_usersが呼び出せる。
  scope :sperior_users, -> { where(sperior: true)}
  
  def User.digest(string)
    cost =
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      user = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      user.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      user.save
    end
  end
  
   # クラスメソッド
  scope :attendancing, -> {
    joins(:attendances)
      .where('attendances.attendance_date = ?', Time.now.localtime('+09:00').to_date)
      .where('attendances.arriving_at < ?', DateTime.current)
      .where('attendances.leaving_at is null')
  }

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["id", "name", "email", "affiliation", "employee_number", "uid", "password",
     "basic_time", "designated_work_start_time", "designated_work_end_time"]
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: :edit
  before_action :superior_user, only: :edit
  before_action :admin_user, only: [:index, :destroy, :edit_basic_info, :update_basic_info]
  before_action :admin_or_correct_user, only: [:edit, :update]
  before_action :set_one_month, only: :show
  
  def index
   @users = User.all
    respond_to do |format|
      format.html do
          #html用の処理を書く
      end 
      format.csv do
          #csv用の処理を書く
          send_data render_to_string, filename: "(ファイル名).csv", type: :csv
      end
    end
   if params[:search]
      @user = User.where('LOWER(name) LIKE ?', "%#{params[:search][:name].downcase}%").paginate(page: params[:page])
   else
      @user = User.paginate(page: params[:page])
   end
  end

  def import
    User.import(params[:file])
    redirect_to users_url
  end

  def show
    if @user.admin?
      flash[:info] = "管理者の勤怠画面は表示されません。"
      redirect_to users_url
    end
    @worked_sum = @attendances.where.not(started_at: nil).count
    @superiors = User && User.where(superior: true).where.not(id: current_user.id)
    # 上長画面で一ヶ月分勤怠申請のお知らせをカウントする
    if @user.superior == true
      @monthly_confirmation_count = Attendance.where(monthly_confirmation_approver_id: @user.id, monthly_confirmation_status: 1).count
      @change_confirmation_count = Attendance.where(change_confirmation_approver_id: @user.id, change_confirmation_status: 1).count
      @overwork_count = Attendance.where(overwork_approver_id: @user.id, overwork_status: 1).count
    end
    @approver = @user.attendances.find_by(worked_on: @first_day)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes!(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to users_url
    else
      flash[:danger] = "ユーザー情報の更新に失敗しました。"
      redirect_to users_url
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
    @users = User.all
  end
  
  def update_basic_info
    @users = User.all
      @users.each do |users|
        if users.update_attributes(basic_info_params)
          flash[:success] = "基本情報を更新しました。"
        else
          flash[:danger] = "更新が失敗しました。<br>" + @user.errors.full_messages.join("<br>")
        end
      end
    redirect_to @users
  end
  
  def working_employee
    @users = User.all.includes(:attendances)
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :affiliation, :employee_number, :uid, :password, :password_confirmation, :designated_work_start_time, :designated_work_end_time)
    end
    
    def basic_info_params
      params.require(:user).permit(:basic_time, :work_time)
    end
    
    def monthly_update_params
      #debugger
      params.require(:user).permit(attendances: [:date, :monthly_confirmation_approver_id, :monthly_confirmation_status, :overday_check])[:attendances]
    end
    
    def admin_or_correct_user
    @user = User.find(params[:id]) if @user.blank?
      unless current_user?(@user) || current_user.admin?
        flash[:danger] = "アクセス権限がありません。"
        redirect_to(root_url)
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
  
  def overtimes(overtime, finish)
    format("%.2f", (((overtime.hour - finish.hour) * 60) + (overtime.min - finish.min)) / 60.0)
  end
end

app/views/users/_form.html.erb
<%= form_with model: @users, local: true, method: :patch do |f| %>
  <%= render 'shared/error_messages', object: @users %>

  <%= f.label "名前", class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>
  
  <%= f.label "メールアドレス", class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label "所属", class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>
  
  <%= f.label "社員番号", class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :employee_number, class: "form-control" %>
  
  <%= f.label "カードID", class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :uid, class: "form-control" %>
  
  <%= f.label "パスワード", class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>
  
  <%= f.label "基本勤務時間", class: "label-#{yield(:class_text)}" %>
  <%= f.time_select :basic_time, class: "form-control" %>
  
  <%= f.label "指定勤務開始時間", class: "label-#{yield(:class_text)}" %>
  <%= f.time_select :designated_work_start_time, class: "form-control" %>
  
  <%= f.label "指定勤務終了時間", class: "label-#{yield(:class_text)}" %>
  <%= f.time_select :designated_work_end_time, class: "form-control" %>
  
  <%= f.submit "更新", class: "btn btn-primary btn-block btn-signup btn-#{yield(:button_text)}" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title,"Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "基本情報の修正") %>
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '編集') %>

<h1>基本情報の更新</h1>
<div class="row">
 <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
      <%= render 'shared/error_messages', object: @users %>
      
      <%= f.label :basic_time, "基本勤務時間", class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :basic_time, class: "form-control" %>
      
      <%= f.label :work_time, "指定勤務時間", class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :work_time, class: "form-control" %>

      <!--<div class="center">
        < %= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
      </div>-->
    <% end %>
  </div>
</div>
  

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>ユーザー一覧</h1>

<div class="row container">
  <div class="col-md-4 col-md-offset-1">
    <div class="csv_holder">
      <%= form_tag import_users_path, method: :post, multipart: true do |f| %>
        <div class="search_item">
          <%= submit_tag 'ファイル選択', class: %i(csv_input_btn), type: 'button', onclick: "$('#file_input').click();" %>
          <%= text_field_tag 'filename',"", id: "filename", disabled: true %>
          <%= file_field_tag :file, id: "file_input", style: "display: none;", onchange: "file_selected($(this));" %>
        </div>
        <div>
          <%= submit_tag "CSVインポート", class: "btn btn-primary" %>
        </div>
      <% end %>
  </div>
</div>

<div class="col-md-10 col-md-offset-1">
  <table class="table table-condensed table-hover" id="table-users">
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></br>
          <% if current_user.admin? && !current_user?(user) %>
            <%= link_to "削除", user, method: :delete, class: "btn btn-md btn-primary",
                data: { confirm:"削除してよろしいですか？" } %></br>
            <div class="panel-group">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h4 class="panel-title">
                    <a data-toggle="collapse" href="#collapse<%= user.id %>"><button type="submit" class="btn btn-primary">編集</button></a>
                  </h4>
                </div>
                
                <div id="collapse<%= user.id %>" class="panel-collapse collapse">
                  <ul class="list-group">
                    <%= form_with model: user, url: user_path(user), local: true, method: :patch do |f| %>
                      <%= render 'shared/error_messages', object: @users %>
                    
                      <%= f.label "名前", class: "label-#{yield(:class_text)}" %>
                      <%= f.text_field :name, class: "form-control" %>
                      
                      <%= f.label "メールアドレス", class: "label-#{yield(:class_text)}" %>
                      <%= f.email_field :email, class: "form-control" %>
                      
                      <%= f.label "所属", class: "label-#{yield(:class_text)}" %>
                      <%= f.text_field :affiliation, class: "form-control" %>
                      
                      <%= f.label "社員番号", class: "label-#{yield(:class_text)}" %>
                      <%= f.text_field :employee_number, class: "form-control" %>
                      
                      <%= f.label "カードID", class: "label-#{yield(:class_text)}" %>
                      <%= f.text_field :uid, class: "form-control" %>
                      
                      <%= f.label "パスワード", class: "label-#{yield(:class_text)}" %>
                      <%= f.password_field :password, class: "form-control" %>
                      
                      <%= f.label "基本勤務時間", class: "label-#{yield(:class_text)}" %>
                      <%= f.time_select :basic_time, class: "form-control" %>
                      
                      <%= f.label "指定勤務開始時間", class: "label-#{yield(:class_text)}" %>
                      <%= f.time_select :designated_work_start_time, class: "form-control" %>
                      
                      <%= f.label "指定勤務終了時間", class: "label-#{yield(:class_text)}" %>
                      <%= f.time_select :designated_work_end_time, class: "form-control" %>
                      
                      <%= f.submit "更新", class: "btn btn-primary btn-block btn-signup btn-#{yield(:button_text)}" %>
                    <% end %>
                    <!--< %= render 'users/form' %>-->
                  </ul>
                </div>
              </div>
            </div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          入力エラーが<%= @user.errors.count %>件ありました。
        </div>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_with model: @user, url: users_path(@user), local: true, method: :post do |f| %>

      <%= f.label "名前", class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :name, class: "form-control" %>
      
      <%= f.label "メールアドレス", class: "label-#{yield(:class_text)}" %>
      <%= f.email_field :email, class: "form-control" %>
      
      <%= f.label "所属", class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :affiliation, class: "form-control" %>
      
      <%= f.label "社員番号", class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :employee_number, class: "form-control" %>
      
      <%= f.label "カードID", class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :uid, class: "form-control" %>
      
      <%= f.label "パスワード", class: "label-#{yield(:class_text)}" %>
      <%= f.password_field :password, class: "form-control" %>
      
      <%= f.label "基本勤務時間", class: "label-#{yield(:class_text)}" %>
      <%= f.time_select :basic_time, class: "form-control" %>
      
      <%= f.label "指定勤務開始時間", class: "label-#{yield(:class_text)}" %>
      <%= f.time_select :designated_work_start_time, class: "form-control" %>
      
      <%= f.label "指定勤務終了時間", class: "label-#{yield(:class_text)}" %>
      <%= f.time_select :designated_work_end_time, class: "form-control" %>
      
      <%= f.submit "新規作成", class: "btn btn-primary btn-block btn-signup btn-#{yield(:button_text)}" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td>
        <% if current_user?(@user) %>
          <%= link_to "←", user_path(date: @first_day.prev_month), class: "btn btn-primary" %>
        <% end %>
        <%= l(@first_day, format: :middle) %>　時間管理表
        <% if current_user?(@user) %>
          <%= link_to "→", user_path(date: @first_day.next_month), class: "btn btn-primary" %>
        <% end %>
      </td>
      <td>指定勤務開始時間　<%= format_basic_info(@user.designated_work_start_time) %><br>
          指定勤務終了時間　<%= format_basic_info(@user.designated_work_end_time) %></td>
      <td colspan="2">基本時間　<%= format_basic_info(@user.basic_time) %></td>
      <td>初日　<%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td>所属　<%= @user.affiliation.present? ? @user.affiliation : "未所属" %></td>
      <td>氏名　<%= @user.name %></td>
      <td>コード</td>
      <td>出勤日数<%= @worked_sum %>日</td>
      <td>締め　<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<div class="hover">
  <!--上長で（自分かどうか）&未承認だったら申請のお知らせの表示・未承認のものがあれば文字は赤色-->
  <% if current_user?(@user) %>
    <% if current_user.superior? %>
      <% unless @monthly_confirmation_count == nil %>
        <% if @monthly_confirmation_count > 0 %>
          <div class="border border-danger text text-danger">
            <%= link_to "【所属長承認申請のお知らせ】", monthly_confirmation_form_user_attendances_path(@user), remote: true, class: 'text text-danger' %>
              <div id="monthly-confirmation-form-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
            <!-- 所属長承認の件数をカウントする-->
              <%= @monthly_confirmation_count %>件のお知らせがあります
          </div>
        <% else %>
          <p>【所属長承認申請のお知らせ】</p>
        <% end %>
      <% end %>
      
      <% unless @change_confirmation_count == nil %>
        <% if @change_confirmation_count > 0 %>
          <div class="border border-danger text text-danger">
            <%= link_to "【勤怠変更申請のお知らせ】", attendances_change_confirmation_form_user_path(@user), remote: true, class: 'text text-danger' %>
              <div id="change-confirmation-form-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
              <%= @change_confirmation_count %>件のお知らせがあります
          </div>
        <% else %>
          <p>【勤怠変更申請のお知らせ】</p>
        <% end %>
      <% end %>
      
      <% unless @overwork_count == nil %>
        <% if @overwork_count > 0 %>
          <div class="border border-danger text text-danger">
            <%= link_to "【残業申請のお知らせ】", update_overtime_form_user_attendance_path(@user), remote: true, class: 'text text-danger' %>
            <div id="update-overtime-form-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
            <%= @overwork_count %>件のお知らせがあります
          </div>
        <% else %>
          <p>【残業申請のお知らせ】</p>
        <% end %>
      <% end %>
            
    <% end %>
  <% end %>
</div>

<div class="btn-users-show">
    <% if current_user?(@user) %>
    <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
    <%= link_to "CSV出力", csv_output_user_attendances_path(user_id: @user, format: :csv), key: @first_day, class: "btn btn-primary" %><br>
    <%= link_to "勤怠修正ログ（承認済）", attendances_index_user_path(@user), :style=>"color:white;", class: "btn btn-primary btn-sm" %>
    <% end %>
</div>

<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th rowspan = "3">残業申請</th>
        <th rowspan = "3">日付</th>
        <th rowspan = "3">曜日</th>
        <th colspan = "7">【実績】</th>
        <th colspan = "7">所定外勤務</th>

      </tr>
      <tr>
        <th colspan = "3">出社</th>
        <th colspan = "3">退社</th>
        <th rowspan = "2">在社時間</th>
        <th rowspan = "2">備考</th>
        <th colspan = "3">終了予定時間</th>
        <th rowspan = "2">時間外時間</th>
        <th rowspan = "2">業務処理内容</th>
        <th rowspan = "2">指示者確認㊞</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @attendances.each do |day| %>
        <tr>
          <td><% if current_user?(@user) %>
                <%= link_to "残業申請", apply_overtime_form_user_attendance_path(@user, day), remote: true, :style=>"color:white;", class: "btn btn-sm btn-primary" %>
              <% end %></td>
          <td><%= l(day.worked_on, format: :short) %></td>
          
          <td>
            <% if day.worked_on.wday == 6 %>
              <%= $days_of_the_week[6] = nil %>
              <font color="Blue">土</font>
            <% end %> 
            <% if day.worked_on.wday == 0 %>
              <%= $days_of_the_week[0] = nil %>
              <font color="Red">日</font>
            <% end %>
            <%= $days_of_the_week[day.worked_on.wday] %>
          </td>
            <td><%= l(day.started_at, format: :hour) if day.started_at.present? %></td>
            <td><%= l(day.started_at, format: :minute) if day.started_at.present? %></td>
          <td>
            <% if current_user?(@user) %>
           　  <% if btn_text = attendance_state(day) && day.started_at.blank? %>
                <%= link_to "出社", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
              <% end %>
            <% end %>
          </td>
            <td><%= l(day.finished_at, format: :hour) if day.finished_at.present? %></td>
            <td><%= l(day.finished_at, format: :minute) if day.finished_at.present? %></td>
           <td>
            <% if current_user?(@user) %>
           　  <% if btn_text = attendance_state(day) && day.started_at.present? && day.finished_at.nil? %>
                <%= link_to "退社", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
              <% end %>
            <% end %>
          </td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= str_times = working_times(day.started_at, day.finished_at) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td></td>
          <td></td>
          <td></td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? && day.overtime.present? %>
              <%= overtimes(day.overtime, current_user.designated_work_end_time) %>
            <% end %>
            </td>
          <td><%= day.task_memo %></td>
          <td>
            <% unless day.change_confirmation_status == nil? %>
              <% if day.change_confirmation_status == 1 %>
                <%= User.find(day.change_confirmation_approver_id).name %>へ勤怠編集申請中
              <% elsif day.change_confirmation_status == 2 %>
                <%= User.find(day.change_confirmation_approver_id).name %>から勤怠編集承認済
              <% elsif day.change_confirmation_status == 3 %>
                <%= User.find(day.change_confirmation_approver_id).name %>から勤怠編集否認
              <% end %>
            <% end %>
            <% unless day.overwork_status == nil? %>
              <% if day.overwork_status == 1 %>
                <%= User.find(day.overwork_approver_id).name %>へ残業申請中
              <% elsif day.overwork_status == 2 %>
                <%= User.find(day.overwork_approver_id).name %>より残業承認済
              <% elsif day.overwork_status == 3 %>
                <%= User.find(day.overwork_approver_id).name %>より残業否認
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>

    <tfoot>
      <!--rowspan:縦結合、colspan：横結合-->
      <tr>
        <td></td>
        <td colspan="2"></td>
        <td colspan="6"></td>
        <td><%= format("%.2f", @total_working_times.to_f) %></td>
        <td colspan="6"></td>
        <td class="table-body">所属長承認
          <% unless @approver == nil %>
            <% if @approver.monthly_confirmation_status == 1 %>
              <%= User.find(@approver.monthly_confirmation_approver_id).name %>へ申請中
            <% elsif @approver.monthly_confirmation_status == 2 %>
              <%= User.find(@approver.monthly_confirmation_approver_id).name %>から承認済
            <% elsif @approver.monthly_confirmation_status == 3 %>
              <%= User.find(@approver.monthly_confirmation_approver_id).name %>から否認
            <% else %>
              未
            <% end %>
          <% end %>
          <% if current_user?(@user) %>
            <%= form_with model: @attendances, url: monthly_confirmation_user_attendances_path(@user), method: :patch do |ma| %>
              <%= ma.collection_select :monthly_confirmation_approver_id, @superiors, :id, :name, {include_blank: true} %>
              <%= ma.hidden_field :date, :value => @first_day %>
              <!--< %= #ma.hidden_field :user_id, @user.id %>-->
              <%= ma.submit "申請", class: "btn btn-primary btn-block btn-sm" %>
            <% end %>
          <% end %>
        </td>
      </tr>
    </tfoot>    
  </table>
</div>
<div id="apply-overtime-form-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/working_employee.html.erb
<% provide(:title, 'Working Employee') %>
<h1>出勤中社員一覧</h1>

<div class="col-md-10 col-md-offset-1">
  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th>社員番号</th>
        <th>氏名</th>
      </tr>
    </thead>
    
    <tbody>
      <% @users.each do |user| %>
        <% user.attendances.each do |attendance| %>
          <% if (Date.current == attendance.worked_on) && attendance.started_at != nil && attendance.finished_at == nil %>
        <tr>
          <td><%= user.employee_number %></td>
          <td><%= user.name %></td>
        </tr>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>