config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'bases/new'

  get 'attendances/update'

  get 'users/new'

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  get     '/login', to: 'sessions#new'
  post    '/login', to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'
  
  #勤怠修正ログ
  resources :attendance_logs
  
  
  resources :users do
    collection {post :import}
    member do
      get   'edit_basic_info'
      patch 'update_basic_info'
      get   'working_employee'
      get   'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get   'search'
      
      get   'attendances/change_confirmation'
      post  'attendances/change_confirmation'
      patch 'attendances/change_confirmation'
      
      get   'attendances/change_confirmation_form'
      post  'attendances/change_confirmation_form'
      
      get   'attendances/index'
      post  'attendances/index'
      patch 'attendances/index'
      
    end
    resources :attendances, only: :update do
      member do
        #残業申請送信フォーム
        get   'apply_overtime_form'
  
        #残業申請
        patch 'apply_overtime'
        
        #残業申請のお知らせフォーム
        get   'update_overtime_form'
        
        #残業承認
        patch 'update_overtime'
        
      end
      collection do
        #一ヶ月分の申請
        patch 'monthly_confirmation'

        #上長画面一ヶ月分勤怠申請のお知らせフォーム
        get   'monthly_confirmation_form'
        patch 'monthly_update'
        
        get   'csv_output'
      end
    end
  end
  
  resources :bases
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
    
  attr_accessor :overday_check
  attr_accessor :tomorrow_check
  attr_accessor :edit_one_month_check
  attr_accessor :overwork_check
  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
  
  validate :finished_at_is_invaild_without_a_started_at
  validate :started_at_than_finished_at_fast_if_invalid
  
  def finished_at_is_invaild_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end
  
  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
      errors.add(:started_at, "より早い退勤時間は無効です") if started_at > finished_at
    end
  end
  
  def finished_at_is_invaild_without_a_started_at_for_edit
    errors.add(:edit_started_at, "が必要です") if edit_started_at.blank? && edit_finished_at.present?
  end
  
  def started_at_than_finished_at_fast_if_invalid_for_edit
    if edit_started_at.present? && edit_finished_at.present?
      errors.add(:edit_started_at, "より早い退勤時間は無効です") if edit_started_at > edit_finished_at
    end
  end
  
  #enum monthly_confirmation_status: { nothing: 0, pending: 1, approval: 2, denial: 3 }
  
  # 【所属長承認のお知らせ】一ヶ月支持者確認がログインユーザーで、ステータスが未承認かどうか＆何月分の勤怠
  def self.monthly_confirmation(current_user)
    attendances = self.where(monthly_confirmation_status: :pending, monthly_confirmation_approver_id: current_user.id)
    year_month_arr = []
    attendances.all.each do |attendance|
      year_month_arr << attendance.attendance_date.year.to_s + attendance.attendance_date.month.to_s
    end
    year_month_arr.uniq.count
  end
  
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: [:edit_one_month, :change_confirmation, :update_one_month, :index]
  before_action :logged_in_user, only: [:update, :edit_one_month, :index]
  before_action :admin_or_correct_user, only: [:update, :edit_one_month, :update_one_month]
  before_action :set_one_month, only: :edit_one_month
  
  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"
  
  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end
  
  def edit_one_month
    @attendance = Attendance.where(params[:id])
    @superiors = User.where(superior: true).where.not(id: current_user.id)
    if @user.superior == true
      @change_confirmation_count = Attendance.where(change_confirmation_approver_id: @user.id, change_confirmation_status: "pending").count
    end
    time.edit_finished_at.day + 1 if [:tomorrow_check] == "1"
  end
  
  def change_confirmation
    ActiveRecord::Base.transaction do
      attendances_params.each do |id, item|
        if item[:change_confirmation_approver_id].present?
          if item[:note].blank?
            flash[:danger] = "備考を入力してください。"
            redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
          elsif item["edit_started_at(4i)"].blank? || item["edit_started_at(5i)"].blank? || item["edit_finished_at(4i)"].blank? || item["edit_finished_at(5i)"].blank?
            flash[:danger] = "変更申請したい時間を入力してください。"
            redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
          else
            unless item[:tomorrow_check] == "1"
              if (item["edit_started_at(4i)"] > item["edit_finished_at(4i)"]) || 
                 ((item["edit_started_at(4i)"] == item["edit_finished_at(4i)"]) && (item["edit_started_at(5i)"] > item["edit_finished_at(5i)"]))
                 flash[:danger] = "出勤時間より早い退勤時間は無効です。"
                 redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
            #if item[:edit_started_at].present? && item[:edit_finished_at].present?
              #if item[:edit_started_at] > item[:edit_finished_at]
                #flash[:danger] = "出勤時間より早い退勤時間は無効です。"
                #redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
              end
            end
          end
          item[:change_confirmation_status] = "1"
          attendance = Attendance.find(id)
          attendance.update_attributes!(item)
        end
      end
      flash[:success] = "勤怠変更の申請を送信しました。"
      redirect_to user_url(current_user) and return
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "無効な入力データがあった為、申請をキャンセルしました。"
    redirect_to attendances_edit_one_month_user_url(date: params[:date])
    #debugger
  end
  
  def change_confirmation_form
    @user = User.find(params[:id])
    @attendance_date = Attendance.where(attendance_date: current_user.id)
    @first_day = params[:date].nil? ? Date.current.beginning_of_month : params[:date].to_date
    @superiors = User.where(superior: true).where.not(id: current_user.id)
    @attendances = Attendance.where(change_confirmation_status: 1, change_confirmation_approver_id: current_user.id).order(user_id: "ASC", worked_on: "ASC").group_by(&:user_id)
    @change_confirmation_count = Attendance.where(change_confirmation_approver_id: current_user.id, change_confirmation_status: 1).count
  end
  
  def update_one_month
    ActiveRecord::Base.transaction do
      attendances_params.each do |id, item|
        if item[:edit_one_month_check] == "1"
          attendance = Attendance.find(id)
          if item[:change_confirmation_status] == "2"
            attendance.changed_started_at = attendance.started_at if attendance.changed_started_at.nil?
            attendance.changed_finished_at = attendance.finished_at if attendance.changed_finished_at.nil?
            item[:started_at] = attendance.edit_started_at
            item[:finished_at] = attendance.edit_finished_at
          end
          attendance.update_attributes!(item)
        end
      end
    end
    flash[:info] = "勤怠変更申請情報を更新処理しました。ご確認ください。"
    redirect_to user_url(current_user.id)
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "無効な入力データがあった為、更新処理をキャンセルしました。"
    redirect_to user_url(current_user.id)
  end
  
  def index
    @attendances = Attendance.where(change_confirmation_status: 2).order(worked_on: "ASC")
  end
  
  #一ヶ月分の勤怠申請
  def monthly_confirmation
    @user = User.find(params[:user_id])
    attendance = @user.attendances.find_by(worked_on: params[:attendance][:date])
    if params[:attendance][:monthly_confirmation_approver_id].blank?
      flash[:danger] = "申請先を入力してください"
      redirect_to user_url(current_user)
    else
      params[:attendance][:monthly_confirmation_status] = 1
      attendance.update_attributes(monthly_confirmation_params)
      flash[:success] = "1ヶ月分の勤怠申請を送信しました。"
      redirect_to user_url(current_user)
    end
  end
  
    #上長承認モーダル画面・ユーザーからの1ヶ月分勤怠
  def monthly_confirmation_form
    @user = User.find(params[:user_id])
    @attendance_date = Attendance.where(attendance_date: current_user.id)
    @first_day = params[:date].nil? ? Date.current.beginning_of_month : params[:date].to_date
    @superiors = User.where(superior: true).where.not(id: current_user.id)
    @attendances = Attendance.where(monthly_confirmation_status: 1, monthly_confirmation_approver_id: current_user.id).order(user_id: "ASC", worked_on: "ASC").group_by(&:user_id)
    @@monthly_confirmation_count = Attendance.where(monthly_confirmation_approver_id: current_user.id, monthly_confirmation_status: 1).count
  end
  
  def monthly_update
    p params
    ActiveRecord::Base.transaction do
      monthly_update_params.each do |id, item|
        if item[:overday_check] == "1" && item[:monthly_confirmation_status] == "2"
          attendance = Attendance.find(id)
          attendance.update_attributes!(item)
        end
      end
    end
    flash[:info] = "1ヶ月分の勤怠申請を更新処理しました。ご確認ください。"
    redirect_to user_url(current_user.id)
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "無効な入力データがあった為、更新処理をキャンセルしました。"
    redirect_to user_url(current_user.id)
  end
  
  def apply_overtime_form
    @attendance = Attendance.find(params[:id])
    @user = User.find(params[:user_id])
    @superiors = User.where(superior: true).where.not(id: current_user.id)
  end
  
  def apply_overtime
    @user = User.find(params[:user_id])
    attendance = Attendance.find(params[:id])
    if params[:attendance][:overwork_approver_id].present?
      if params[:attendance][:task_memo].blank?
        flash[:danger] = "業務処理内容を入力してください。"
        redirect_to user_url(@user) and return
      elsif params[:attendance]["overtime(4i)"].blank? || params[:attendance]["overtime(5i)"].blank?
        flash[:danger] = "残業申請したい時間を入力してください。"
        redirect_to user_url(@user) and return
      elsif attendance.finished_at.blank?
        flash[:danger] = "退社ボタンを押下するか、勤怠変更申請にて終了予定時間を申請してください。"
        redirect_to user_url(@user) and return
      end
      params["overtime(3i)"] + 1 if params[:tomorrow_check] == "1"
      params[:attendance][:overwork_status] = "1"
      attendance.update_attributes!(apply_overtime_params)
    else
      flash[:danger] = "申請先を入力してください"
      redirect_to user_url(current_user) and return
    end
    flash[:success] = "残業申請を送信しました。"
    redirect_to user_url(@user) and return
  end
  
  def update_overtime_form
    @user = User.find(params[:user_id])
    @attendance_date = Attendance.where(attendance_date: current_user.id)
    @first_day = params[:date].nil? ? Date.current.beginning_of_month : params[:date].to_date
    @superiors = User.where(superior: true).where.not(id: current_user.id)
    @attendances = Attendance.where(overwork_status: 1, overwork_approver_id: current_user.id).order(user_id: "ASC", worked_on: "ASC").group_by(&:user_id)
    @overwork_count = Attendance.where(overwork_approver_id: current_user.id, overwork_status: 1).count
  end
  
  def update_overtime
    ActiveRecord::Base.transaction do
      update_overtime_params.each do |id, item|
        if item[:overwork_check] == "1"
          attendance = Attendance.find(id)
          if item[:overwork_status] == "2"
            item[:overtime] = attendance.overtime
          end
          attendance.update_attributes!(item)
        end
      end
    end
    flash[:info] = "勤怠変更申請情報を更新処理しました。ご確認ください。"
    redirect_to user_url(current_user.id)
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "無効な入力データがあった為、更新処理をキャンセルしました。"
    redirect_to user_url(current_user.id)
  end
  
   def csv_output
    user = User.find(params[:user_id])
    @first_day = params[:date].nil? ? Date.current.beginning_of_month : params[:date].to_date
    @last_day = @first_day.end_of_month
    @attendances = user.attendances.where(worked_on: @first_day..@last_day).order(:worked_on)
    send_data render_to_string, filename: "attendances.csv", type: :csv
   end
  
  
  private
  
    def attendances_params
      params.require(:user).permit(attendances: [:started_at, :finished_at, :edit_started_at, :edit_finished_at, :note, :change_confirmation_approver_id, :change_confirmation_status, :tomorrow_check, :edit_one_month_check])[:attendances]
    end
    
    def monthly_confirmation_params
      #debugger
      params.require(:attendance).permit(:monthly_confirmation_approver_id, :monthly_confirmation_status)
    end
    
    def monthly_update_params
      #debugger

app/helpers/attendances_helper.rb
module AttendancesHelper
  
  def attendance_state(attendance)
    if Date.current == attendance.worked_on
      return '出社' if attendance.started_at.nil?
      return '退社' if attendance.started_at.present? && attendance.finished_at.nil?
    end
      false
  end
  
  def attendance_count
    Attendance.where(user_id: params[:id], attendance_date: Time.new(@first_day.year,@first_day.month).all_month).select("finished_at").count
  end
  
  # 在社時間計上用
  def working_hours(a,b)
    started_at = Time.mktime(a.year, a.month, a.day, a.hour, a.min, 0, 0)
    finished_at = Time.mktime(b.year, b.month, b.day, b.hour, b.min, 0, 0)
    #(((leaving_at - arriving_at) / 60) / 60).truncate()
    (Time.parse("1/1") + (finished_at - started_at)).strftime("%H時間%M分")
  end
  
  # 引数の時刻データの秒を０にして差を求める
  def times(x,y)
    c = Time.mktime(x.year, x.month, x.day, x.hour, x.min, 0, 0)
    d = Time.mktime(y.year, y.month, y.day, y.hour, y.min, 0, 0)
    (d - c).to_i
  end

  
  def working_times(start, finish)
    format("%.2f", (((finish - start) / 60) / 60.0))
  end
  
  def overtimes(overtime, finish)
    format("%.2f", ((overtime.hour - finish.hour) + (overtime.min - finish.min) / 60.0))
  end
  
end

app/views/attendances/_apply_overtime_form.html.erb
<div class="modal-dialog modal-lg">
  <div class="modal-content">
    <div class="apply_overtime_form">
      <div id="black">
      <%= form_with model: @attendance, url: apply_overtime_user_attendance_path(@user, @attendance), method: :patch do |f| %>
        <h2>【残業申請】</h2>
          <table class = "table table-bordered table-condensed table-hover" id = "table-attendances">
            <thead>
              <thead>
                <tr>
                  <th>日付</th>
                  <th>曜日</th>
                  <th>終了予定時間</th>
                  <th>翌日</th>
                  <th>業務処理内容</th>
                  <th>指示者確認㊞</th>
                </tr>
            </thead>
            <tbody>
              <tr>
                <!--日付-->
                <td class="center"><%= l(@attendance.worked_on, format: :short) %></td>
                <!--曜日-->
                <td class="center"><%= $days_of_the_week[@attendance.worked_on.wday] %></td>
                <td class="center"><%= f.time_select :overtime, {include_blank: true}, class: "form-control bootstrap-date" %></td>
                <td class="center"><%= f.check_box :tomorrow_check, {:checked => false}, 1 %></td>
                <td class="center"><%= f.text_field :task_memo, class: "form-control" %></td>
                <td class="center"><%= f.collection_select :overwork_approver_id, @superiors, :id, :name, {include_blank: true} %></td>
                <!--< %= f.hidden_field :user_id, @user.id %>-->
              </tr>
            </tbody>
          </table>
          <%= f.submit "変更を送信する", class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_change_confirmation_form.html.erb
<div class="modal-dialog modal-lg">
  <div class="modal-content">
    <div class="change_confirmation_form">
      <div id="black">
      <%= @change_confirmation_count %>

        <% @attendances.each do |user_id, user| %>
          <h2><%= User.find(user_id).name %>からの勤怠変更申請</h2>
          
          <%= form_with model: @user, url: attendances_update_one_month_user_path, local: true, method: :patch do |f| %>
            <% user.each do |a| %>
            <%= f.fields_for "attendances[]", a do |attendances| %>
              <table class = "table table-bordered table-condensed table-hover" id="table-attendances">
                <thead>
                  <thead>
                    <tr>
                      <th rowspan = "3">日付</th>
                      <th rowspan = "3">曜日</th>
                      <th colspan = "4">変更前</th>
                      <th colspan = "4">変更後</th>
                      <th rowspan = "3">備考</th>
                      <th rowspan = "3">指示者確認㊞</th>
                      <th rowspan = "3">変更</th>
                      <th rowspan = "3">勤怠を確認する</th>
              
                    </tr>
                    <tr>
                      <th colspan = "2">出社</th>
                      <th colspan = "2">退社</th>
                      <th colspan = "2">出社</th>
                      <th colspan = "2">退社</th>
              
                    </tr>
                    <tr>
                      <th>時</th>
                      <th>分</th>
                      <th>時</th>
                      <th>分</th>
                      <th>時</th>
                      <th>分</th>
                      <th>時</th>
                      <th>分</th>
                    </tr>
                </thead>
                <tbody>
                  <tr>
                    <!--日付-->
                    <td class="center"><%= l(a.worked_on, format: :short) %></td>
                    <!--曜日-->
                    <td class="center"><%= $days_of_the_week[a.worked_on.wday] %></td>
                    <td class="center"><%= l(a.started_at, format: :hour) if a.started_at.present? %></td>
                    <td class="center"><%= l(a.started_at, format: :minute) if a.started_at.present? %></td>
                    <td class="center"><%= l(a.finished_at, format: :hour) if a.finished_at.present? %></td>
                    <td class="center"><%= l(a.finished_at, format: :minute) if a.finished_at.present? %></td>
                    <td class="center"><%= l(a.edit_started_at, format: :hour) %></td>
                    <td class="center"><%= l(a.edit_started_at, format: :minute) %></td>
                    <td class="center"><%= l(a.edit_finished_at, format: :hour) %></td>
                    <td class="center"><%= l(a.edit_finished_at, format: :minute) %></td>
                    <td class="center"><%= a.note %></td>
                    <td class="center"><%= attendances.select :change_confirmation_status, [["申請なし", 0],["申請中", 1],["承認", 2],["非承認", 3]], {} %></td>
                    
                    <!--変更のチェックボックス、チェックがないと変更しても反映されない-->
                  　<td><%= attendances.check_box :edit_one_month_check, {:checked => true}, 1 %></td>
                    <!--勤怠を確認するボタン-->
                    <td><%= link_to "確認", user_path(a.user_id, date: a.worked_on.beginning_of_month), :style=>"color:white;", class: "btn btn-sm btn-primary" %></td>
                  </tr>
                </tbody>
              </table>
              <%= attendances.submit "変更を送信する", class: "btn btn-primary btn-sm" %>
          <% end %>
          <% end %>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_monthly_confirmation_form.html.erb
<div class="modal-dialog modal-lg">
  <div class="modal-content">
    <div class="monthly_confirmation_form">
      <div id="black">
        <% @attendances.each do |user_id, attendance| %>
          <% user = User.find(user_id) %>
          <h2><%= user.name %>からの所属長承認申請</h2>
          <%= form_with model: @user, url: monthly_update_user_attendances_path, local: true, method: :patch do |f| %>
            <% attendance.each do |a| %>
              <%= f.fields_for "attendances[]", a do |attendances| %>
                <table class = "table table-bordered table-condensed table-hover" id="table-attendances">
                  <thead>
                    <thead>
                      <tr>
                        <th>月</th>
                        <th>指示者確認㊞</th>
                        <th>変更</th>
                        <th>勤怠を確認する</th>
                      </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <!--日付-->
                      <td class="center"><%= l(a.worked_on, format: :month) %></td>
                      <td class="center"><%= attendances.select :monthly_confirmation_status, [["申請なし", 0],["申請中", 1],["承認", 2],["非承認", 3]], {} %></td>
                      <!--変更のチェックボックス、チェックがないと変更しても反映されない-->
                    　<td><%= attendances.check_box :overday_check, {:checked => true}, 1 %></td>
                      <!--勤怠を確認するボタン-->
                      <td><%= link_to "確認", user_path(a.user_id, date: a.worked_on.beginning_of_month), :style=>"color:white;", class: "btn btn-sm btn-primary" %></td>
                    </tr>
                  </tbody>
                </table>
                <%= attendances.submit "変更を送信する", class: "btn btn-primary btn-sm" %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_update_overtime_form.html.erb
<div class="modal-dialog modal-lg">
  <div class="modal-content">
    <div class="update_overtime_form">
      <div id="black">
        <% @attendances.each do |user_id, attendance| %>
          <% user = User.find(user_id) %>
          <h2><%= user.name %>からの残業申請</h2>
          <%= form_with model: @user, url: update_overtime_user_attendance_path, local: true, method: :patch do |f| %>
            <% attendance.each do |a| %>
              <%= f.fields_for "attendances[]", a do |attendances| %>
                <table class = "table table-bordered table-condensed table-hover" id="table-attendances">
                  <thead>
                    <thead>
                      <tr>
                        <th>日付</th>
                        <th>曜日</th>
                        <th>指定勤務終了時間</th>
                        <th>終了予定時間</th>
                        <th>時間外時間</th>
                        <th>業務処理内容</th>
                        <th>指示者確認㊞</th>
                        <th>変更</th>
                        <th>勤怠を確認する</th>
                      </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <!--日付-->
                      <td class="center"><%= l(a.worked_on, format: :short) %></td>
                      <!--曜日-->
                      <td class="center"><%= $days_of_the_week[a.worked_on.wday] %></td>
                      <td class="center"><%= l(user.designated_work_end_time, format: :time) %></td>
                      <td class="center"><%= l(a.overtime, format: :time) %></td>
                      <td class="center"><%= overtimes(a.overtime, user.designated_work_end_time) %></td>
                      <td class="center"><%= a.task_memo %></td>
                      <td class="center"><%= attendances.select :overwork_status, [["申請なし", 0],["申請中", 1],["承認", 2],["非承認", 3]], {} %></td>
                      
                      <!--変更のチェックボックス、チェックがないと変更しても反映されない-->
                    　<td><%= attendances.check_box :overwork_check, {:checked => true}, 1 %></td>
                      <!--勤怠を確認するボタン-->
                      <td><%= link_to "確認", user_path(a.user_id, date: a.worked_on.beginning_of_month), :style=>"color:white;", class: "btn btn-sm btn-primary" %></td>
                    </tr>
                  </tbody>
                </table>
                <%= attendances.submit "変更を送信する", class: "btn btn-primary btn-sm" %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/attendances/apply_overtime_form.js.erb
$("#apply-overtime-form-modal").html("<%= escape_javascript(render 'apply_overtime_form') %>")
$("#apply-overtime-form-modal").modal("show")

app/views/attendances/change_confirmation_form.js.erb
$("#change-confirmation-form-modal").html("<%= escape_javascript(render 'attendances/change_confirmation_form') %>")
$("#change-confirmation-form-modal").modal("show")

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url: attendances_change_confirmation_user_path(date: @first_day), local: true, method: :patch) do |f| %>
  <div>
    <h1>勤怠編集画面</h1>
    <table class="table table-bordered table-condensed table-hover" id="table-attendances">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出社</th>
          <th>退社</th>
          <th>翌日</th>
          <th>在社時間</th>
          <th>備考</th>
          <th>指示者確認㊞</th>
        </tr>
      </thead>
      <tbody>
        <% @attendances.each do |day| %>
          <%= f.fields_for "attendances[]", day do |attendance| %>
            <tr>
              <td><%= l(day.worked_on, format: :short) %></td>
              <td>
                <% if day.worked_on.wday == 6 %>
                  <%= $days_of_the_week[6] = nil %>
                  <font color="Blue">土</font>
                <% elsif day.worked_on.wday == 0 %>
                  <%= $days_of_the_week[0] = nil %>
                  <font color="Red">日</font>
                <% else %>
                  <%= $days_of_the_week[day.worked_on.wday] %>
                <% end %>
              </td>
                         
             
              <% if Date.current <= day.worked_on && day.finished_at.blank? %>
                <td><%= attendance.time_select :edit_started_at, {include_blank: true}, disabled: true, class: "form-control bootstrap-date" %></td>
                <td><%= attendance.time_select :edit_finished_at, {include_blank: true}, disabled: true, class: "form-control bootstrap-date" %></td>
              <% else %>
                <td><%= attendance.time_select :edit_started_at, {include_blank: true}, class: "form-control bootstrap-date" %></td>
                <td><%= attendance.time_select :edit_finished_at, {include_blank: true}, class: "form-control bootstrap-date" %></td>
              <% end %> 
              <td><%= attendance.check_box :tomorrow_check, {:checked => false}, 1 %></td>
              <td>
                <% if day.started_at.present? && day.finished_at.present? %>
                  <%= format("%.2f", working_times(day.changed_started_at ||= 0, day.changed_finished_at ||= 0)) %>
                <% end %>  
              </td>
              <td><%= attendance.text_field :note, placeholder: "入力必須", class: "form-control" %></td>
              <td>
                <% if Date.current <= day.worked_on && day.finished_at.blank? %>
                  <%= attendance.collection_select :change_confirmation_approver_id, @superiors, :id, :name, {include_blank: true}, disabled: true %>
                <% else %>
                  <%= attendance.collection_select :change_confirmation_approver_id, @superiors, :id, :name, {include_blank: true} %>
                <% end %>
              </td>
            </tr>
          <% end %>
       <% end %>
      </tbody>
    </table>
  </div>
  <div class="row, center">
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-md btn-primary" %><%= f.submit "編集を保存する", class: "btn btn-md btn-primary" %>
  </div>
<% end %>

app/views/attendances/monthly_confirmation_form.js.erb
$("#monthly-confirmation-form-modal").html("<%= escape_javascript(render 'attendances/monthly_confirmation_form') %>")
$("#monthly-confirmation-form-modal").modal("show")

app/views/attendances/update_overtime_form.js.erb
$("#update-overtime-form-modal").html("<%= escape_javascript(render 'update_overtime_form') %>")
$("#update-overtime-form-modal").modal("show")